'use client'

import { useState, useEffect } from 'react'
import type { DreamLog, BirthData } from '@/lib/types'
import type { LLMProvider } from '@/lib/llm'
import { getDreams, getBirthData } from '@/lib/store'
import RecommendationCards from '@/components/RecommendationCards'
import { apiFetch } from '@/lib/apiFetch'

interface StructuredLetter {
  key_patterns: { pattern: string; frequency: number; significance: string }[]
  emotional_arc: string
  dominant_symbol: { name: string; meaning: string }
  recommendations: { action: string; timing: string; why: string }[]
  closing_theme: string
}

type Status = 'idle' | 'loading' | 'done' | 'error'

export default function LettersPage() {
  const [dreams, setDreams] = useState<DreamLog[]>([])
  const [birthData, setBirthData] = useState<BirthData | null>(null)
  const [status, setStatus] = useState<Status>('idle')
  const [statusMessage, setStatusMessage] = useState('')
  const [prose, setProse] = useState('')
  const [structured, setStructured] = useState<StructuredLetter | null>(null)
  const [provider, setProvider] = useState<LLMProvider>('anthropic')
  const [model, setModel] = useState<string | undefined>(undefined)
  const [copied, setCopied] = useState(false)

  const handleShare = async () => {
    const text = `✦ A letter from my unconscious ✦\n\n${prose}\n\n— Generated by Dreamscape`
    if (navigator.share) {
      try { await navigator.share({ text }) } catch { /* cancelled */ }
    } else {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  useEffect(() => {
    getDreams().then(setDreams)
    getBirthData().then(setBirthData)
    const p = (localStorage.getItem('dreamscape_provider') as LLMProvider) || 'anthropic'
    const m = localStorage.getItem('dreamscape_model') || undefined
    setProvider(p)
    setModel(p === 'ollama' ? m : undefined)
  }, [])

  const analyzed = dreams.filter((d) => d.extraction)
  const canGenerate = analyzed.length >= 3

  const handleGenerate = async () => {
    if (!canGenerate || status === 'loading') return

    setStatus('loading')
    setProse('')
    setStructured(null)
    setStatusMessage('')

    const today = new Date().toISOString().split('T')[0]

    try {
      const res = await apiFetch('/api/letter', {
        method: 'POST',
        body: JSON.stringify({ dreams: analyzed, birthData, date: today, provider, model }),
      })

      if (!res.ok) throw new Error('API error')
      if (!res.body) throw new Error('No response body')

      const reader = res.body.getReader()
      const decoder = new TextDecoder()
      let buffer = ''

      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        buffer += decoder.decode(value, { stream: true })

        const events = buffer.split('\n\n')
        buffer = events.pop() || ''

        for (const event of events) {
          if (!event.trim()) continue
          const lines = event.split('\n')
          let eventType = ''
          let dataLine = ''
          for (const line of lines) {
            if (line.startsWith('event:')) eventType = line.slice(6).trim()
            if (line.startsWith('data:')) dataLine = line.slice(5).trim()
          }
          if (!dataLine) continue
          const data = JSON.parse(dataLine)

          if (eventType === 'status') {
            setStatusMessage(data.message)
          } else if (eventType === 'letter') {
            setProse(data.prose)
            setStructured(data.structured)
            setStatus('done')
          } else if (eventType === 'error') {
            setStatus('error')
            setStatusMessage(data.message)
          }
        }
      }
    } catch (err) {
      setStatus('error')
      setStatusMessage('Something went wrong. Please try again.')
    }
  }

  return (
    <div className="max-w-xl mx-auto px-4 pt-8 pb-4 space-y-6">
      {/* Header */}
      <div className="space-y-1">
        <h1
          className="text-2xl font-medium tracking-tight"
          style={{ color: 'var(--text)', fontFamily: 'Georgia, serif' }}
        >
          Dream Letters
        </h1>
        <p className="text-sm" style={{ color: 'var(--muted)' }}>
          A letter synthesized from your recent dreams — patterns, currents, and what your unconscious seems to be saying.
        </p>
      </div>

      {/* Status/CTA */}
      {status !== 'done' && (
        <div className="space-y-3">
          <div
            className="rounded-xl p-4 flex items-center justify-between"
            style={{ background: 'rgba(15,15,26,0.7)', border: '1px solid var(--border)' }}
          >
            <div>
              <div className="text-sm font-medium" style={{ color: 'var(--text)' }}>
                {analyzed.length} analyzed dream{analyzed.length !== 1 ? 's' : ''}
              </div>
              <div className="text-xs mt-0.5" style={{ color: 'var(--muted)' }}>
                {canGenerate
                  ? 'Ready to generate your letter'
                  : `Log ${3 - analyzed.length} more dream${3 - analyzed.length !== 1 ? 's' : ''} to unlock`}
              </div>
            </div>
            {canGenerate && (
              <div
                className="w-2 h-2 rounded-full"
                style={{ background: '#4ade80' }}
              />
            )}
          </div>

          {status === 'loading' && (
            <div className="flex items-center gap-3 px-1">
              <div className="flex gap-1">
                {[0, 1, 2].map((i) => (
                  <div
                    key={i}
                    className="w-1.5 h-1.5 rounded-full"
                    style={{
                      background: 'var(--violet)',
                      animation: `bounce 1.2s infinite ${i * 0.2}s`,
                    }}
                  />
                ))}
              </div>
              <span className="text-sm" style={{ color: 'var(--muted)' }}>
                {statusMessage}
              </span>
            </div>
          )}

          {status === 'error' && (
            <div
              className="rounded-xl p-3 text-sm"
              style={{ background: 'rgba(248,113,113,0.1)', border: '1px solid rgba(248,113,113,0.2)', color: '#f87171' }}
            >
              {statusMessage}
            </div>
          )}

          <button
            onClick={handleGenerate}
            disabled={!canGenerate || status === 'loading'}
            className="w-full py-3.5 rounded-2xl text-sm font-medium transition-all duration-200"
            style={{
              background: canGenerate && status !== 'loading' ? 'var(--violet)' : 'rgba(167,139,250,0.15)',
              color: canGenerate && status !== 'loading' ? '#07070f' : 'rgba(167,139,250,0.4)',
              cursor: !canGenerate || status === 'loading' ? 'not-allowed' : 'pointer',
            }}
          >
            {status === 'loading' ? 'Writing...' : 'Generate Letter ◇'}
          </button>
        </div>
      )}

      {/* Letter display */}
      {status === 'done' && prose && (
        <div className="space-y-6">
          {/* Action buttons */}
          <div className="flex justify-end gap-2">
            <button
              onClick={handleShare}
              className="text-xs px-3 py-1 rounded-full transition-opacity hover:opacity-70"
              style={{ border: '1px solid rgba(167,139,250,0.4)', color: 'var(--violet)' }}
            >
              {copied ? '✓ Copied' : '◇ Share'}
            </button>
            <button
              onClick={() => setStatus('idle')}
              className="text-xs px-3 py-1 rounded-full transition-opacity hover:opacity-70"
              style={{ border: '1px solid var(--border)', color: 'var(--muted)' }}
            >
              ↺ Regenerate
            </button>
          </div>

          {/* The letter */}
          <div
            className="rounded-2xl p-6 space-y-5"
            style={{ background: 'rgba(15,15,26,0.7)', border: '1px solid rgba(167,139,250,0.15)' }}
          >
            <div className="flex items-center gap-2 pb-2" style={{ borderBottom: '1px solid var(--border)' }}>
              <span style={{ color: 'var(--violet)' }}>◇</span>
              <span className="text-xs font-mono uppercase tracking-widest" style={{ color: 'var(--violet)' }}>
                Your Dream Letter
              </span>
            </div>
            <div className="dream-letter text-sm" style={{ color: 'var(--text)' }}>
              {prose.split('\n\n').map((para, i) => (
                <p key={i} className="mb-4 last:mb-0" style={{ lineHeight: '1.85' }}>
                  {para}
                </p>
              ))}
            </div>
          </div>

          {/* Structured insights */}
          {structured && (
            <div className="space-y-5">
              {/* Key patterns */}
              {structured.key_patterns?.length > 0 && (
                <div className="space-y-2">
                  <div className="text-xs font-mono uppercase tracking-widest" style={{ color: 'var(--violet)' }}>
                    Recurring Patterns
                  </div>
                  {structured.key_patterns.map((p, i) => (
                    <div
                      key={i}
                      className="rounded-xl p-3 flex items-start gap-3"
                      style={{ background: 'rgba(15,15,26,0.7)', border: '1px solid var(--border)' }}
                    >
                      <div
                        className="shrink-0 text-xs px-1.5 py-0.5 rounded font-mono mt-0.5"
                        style={{ background: 'rgba(167,139,250,0.1)', color: 'var(--violet)' }}
                      >
                        ×{p.frequency}
                      </div>
                      <div>
                        <div className="text-sm font-medium mb-0.5" style={{ color: 'var(--text)' }}>{p.pattern}</div>
                        <div className="text-xs" style={{ color: 'var(--muted)' }}>{p.significance}</div>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {/* Emotional arc */}
              {structured.emotional_arc && (
                <div
                  className="rounded-xl p-4"
                  style={{ background: 'rgba(129,140,248,0.07)', border: '1px solid rgba(129,140,248,0.15)' }}
                >
                  <div className="text-xs font-mono uppercase tracking-widest mb-2" style={{ color: 'var(--indigo)' }}>
                    Emotional Arc
                  </div>
                  <p className="text-sm italic" style={{ color: 'var(--text)', fontFamily: 'Georgia, serif', lineHeight: '1.7' }}>
                    {structured.emotional_arc}
                  </p>
                </div>
              )}

              {/* Dominant symbol */}
              {structured.dominant_symbol && (
                <div
                  className="rounded-xl p-4"
                  style={{ background: 'rgba(15,15,26,0.7)', border: '1px solid var(--border)' }}
                >
                  <div className="text-xs font-mono uppercase tracking-widest mb-2" style={{ color: 'var(--muted)' }}>
                    Dominant Symbol
                  </div>
                  <div className="text-sm font-medium mb-1" style={{ color: 'var(--violet)' }}>
                    {structured.dominant_symbol.name}
                  </div>
                  <p className="text-sm" style={{ color: 'var(--muted)' }}>
                    {structured.dominant_symbol.meaning}
                  </p>
                </div>
              )}

              {/* Recommendations */}
              {structured.recommendations?.length > 0 && (
                <RecommendationCards recommendations={structured.recommendations} />
              )}

              {/* Closing theme */}
              {structured.closing_theme && (
                <div className="text-center py-4">
                  <p
                    className="text-sm italic"
                    style={{ color: 'var(--muted)', fontFamily: 'Georgia, serif' }}
                  >
                    "{structured.closing_theme}"
                  </p>
                </div>
              )}
            </div>
          )}
        </div>
      )}

      <style>{`
        @keyframes bounce {
          0%, 80%, 100% { transform: translateY(0); opacity: 0.4; }
          40% { transform: translateY(-4px); opacity: 1; }
        }
      `}</style>
    </div>
  )
}
